# Generated by Django 3.2.16 on 2023-02-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('bk_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dstatus', models.CharField(max_length=254)),
                ('licence_no',models.CharField(max_length=50)),
                ('dob',models.CharField(max_length=50)),
                ('gender',models.CharField(max_length=50)),
                ('qualification',models.CharField(max_length=50)),
                ('experience',models.CharField(max_length=50)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departments')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=50)),
                ('end_timne', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('fee_amount', models.CharField(max_length=20)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=225)),
                ('blood_group', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('pstatus', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.login')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_des', models.CharField(max_length=225)),
                ('leave_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_des', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.login'),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule'),
        ),
    ]
