# Generated by Django 3.2.16 on 2023-02-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.FileField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
