# Generated by Django 3.2.16 on 2023-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_image'),
    ]

 
