# Generated by Django 3.2.15 on 2023-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doctor_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dstatus',
            field=models.CharField(max_length=50),
        ),
    ]
