# Generated by Django 3.2.15 on 2023-03-20 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230307_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases', models.CharField(max_length=50)),
                ('alergic', models.CharField(max_length=1000)),
                ('prescription', models.CharField(max_length=1000)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
    ]
