# Generated by Django 3.2.15 on 2023-03-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230323_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lab',
            new_name='labs',
        ),
    ]
