# Generated by Django 3.2.15 on 2023-04-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_upload_lab_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_item', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=1000)),
                ('upload_lab_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.upload_lab_prescription')),
            ],
        ),
    ]
